pipeline Airport_Dat_Pipeline{
    
    block Airport_Dat_Extractor oftype HttpExtractor{
        url:"https://opendata.rhein-kreis-neuss.de/api/explore/v2.1/catalog/datasets/rhein-kreis-neuss-flughafen-weltweit/exports/csv";
    }
    
    block Airport_Dat_TransformInt oftype TextFileInterpreter{    
    }
    
    block Airport_Dat_TransformCsv oftype CSVInterpreter{
        
        delimiter:";";
    }
    
    block Airport_Dat_TransformTable oftype TableInterpreter{
        
        header:false;
        columns:[
            "Lfd. Nummer" oftype integer,
            "Name des Flughafens" oftype text,
            "Ort" oftype text,
            "Land" oftype text,
            "IATA" oftype text,
            "ICAO" oftype text,
            "Latitude" oftype decimal,
            "Longitude" oftype decimal,
            "Altitude" oftype integer
                    ];

    }
    
    block Airport_Dat_Loader oftype SQLiteLoader{
        
        table:"airports";

        
        file: "./airports.sqlite";
    }
    
    Airport_Dat_Extractor
        -> Airport_Dat_TransformInt
        -> Airport_Dat_TransformCsv
        -> Airport_Dat_TransformTable
        -> Airport_Dat_Loader;
    
     
}
