name: CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: List files in the repository for debugging
      run: ls -R  # List all files in the repository for debugging

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r project/requirements.txt  # Install dependencies from requirements.txt

    - name: Run the main pipeline
      run: |
        echo "Running the pipeline script..."
        python project/pipeline.py  # Execute the pipeline script

    - name: Run tests
      run: |
        echo "Running tests..."
        python -m pytest project/tests.py  # Run the test suite using pytest
