name: CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install pytest pandas  # Install pytest and pandas

    - name: List files in the repository for debugging
      run: ls -R  # List all files for debugging purposes

    - name: Make tests.sh executable
      run: chmod +x ./project/tests.sh  # Make tests.sh file executable

    - name: Run tests
      run: ./project/tests.sh  # Run the tests.sh script
