name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Debug requirements.txt
      run: cat requirements.txt  # Debugging step to check contents of requirements.txt

    - name: Install dependencies
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          echo "Error: requirements.txt file not found."
          exit 1
        fi

        # Debugging: Verify that matplotlib and other packages are installed
        pip freeze

    - name: Debug tests.sh
      run: |
        ls -l project/tests.sh  # Check if tests.sh exists and is executable
        file project/tests.sh   # Verify it's a shell script

    - name: Run tests
      run: |
        chmod +x project/tests.sh  # Ensure tests.sh is executable
        ./project/tests.sh         # Run the test script

    - name: Post-test actions
      if: failure()
      run: echo "Tests failed. Please check the logs."
