name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Step to checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas  # Install dependencies (pytest, pandas, etc.)

    - name: Make tests.sh executable
      run: chmod +x tests.sh  # Ensure that tests.sh is executable

    - name: Run tests
      run: .project/tests.sh  # Run the tests.sh script
