name: CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: List files in the repository for debugging
      run: ls -R  # List all files in the repository for debugging

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Use Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install pytest numpy pandas scikit-learn  # Install pytest, pandas, and scikit-learn

    - name: Run tests (pytest)
      run: |
        echo "Running tests with pytest..."
        pytest project/tests.py  # Run tests.py using pytest
        # Alternatively, if there are tests in multiple files, you can run the entire folder:
        # pytest project/ 

    - name: Ensure main_pipeline.py and tests.py are up-to-date
      run: |
        echo "Checking if main_pipeline.py and tests.py are up-to-date"
        ls -l project/pipeline.py  # Check if main_pipeline.py exists in the 'project' folder
        ls -l project/tests.py  # Check if tests.py exists in the 'project' folder
        chmod +x project/tests.py  # Make tests.py executable (if needed, this depends on your setup)
        
    - name: Run main pipeline (if needed)
      run: |
        echo "Running the main pipeline script..."
        python project/pipeline.py  # Run the main pipeline script if required (adjust as necessary)
