name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    - name: Run the Python script
      run: |
        python test.py

    - name: Save Outputs (Artifacts)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Outputs
        path: |
          final_data.csv
          USA_Important_Features.csv
          Brazil_Important_Features.csv
          gdp_brazil_usa.db
